### ISSUE TITLE
Error message if no field selected

### ISSUE THREAD

**Issue by firejake308** [firejake308/internal-references#3]
Received this review on AnkiWeb:

> Thanks for the addon! Doesn't work for me unfortunately. Any suggestions?
> 
> Debuginformationen:
> Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
> Platform: Mac 12.5
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2022-08-13 23:01:04
> Möglicherweise beteiligte Erweiterungen: ⁨Internal References⁩
> 
> Caught exception:
> Traceback (most recent call last):
> File "/Users/fabeyyyyy/Library/Application Support/Anki2/addons21/323026909/insertlink.py", line 189, in accept
> self.insertAnchor()
> File "/Users/fabeyyyyy/Library/Application Support/Anki2/addons21/323026909/insertlink.py", line 143, in insertAnchor
> self.editor.web.eval("focusField(%d);" % self.editor.currentField)
> TypeError: %d format: a number is required, not NoneType

The root cause is that none of the text fields were selected at the time that the user clicked the button. I can fix this by graying out the "add link" button when all text fields lose focus.

**Comment by firejake308** [comment]
This should be fixed as of today
