### ISSUE TITLE
Crash on Anki 2.1.54

### ISSUE THREAD

**Issue by brainexcerpts** [firejake308/internal-references#4]
Awesome addon but seems to need an update as it crashes the browser (suddenly closes) when clicking on either:
![image](https://user-images.githubusercontent.com/8319592/220822613-87352d95-1fd7-4343-bd01-e4a0668498a5.png)

Reopening the browser and trying to create a reference again you would get:

```
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2023-02-23 00:23:45

Caught exception:
Traceback (most recent call last):
  File "C:\Users\vailrodo\AppData\Roaming\Anki2\addons21\323026909\main.py", line 32, in on_result
    if not data_tuple[1] or isinstance(data_tuple[1], QPyNullVariant):
TypeError: 'NoneType' object is not subscriptable
```

Strangely, you can make the error disappear by opening the html editing mode of some card. 
The issue will remain every time I retry though.

Also, not selecting cards with the browser's buttons, and clicking 'ok' too early, when creating a reference will crash with the following error:

```
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2023-02-23 00:23:45

Caught exception:
Traceback (most recent call last):
  File "C:\Users\vailrodo\AppData\Roaming\Anki2\addons21\323026909\insertlink.py", line 189, in accept
    self.insertAnchor()
  File "C:\Users\vailrodo\AppData\Roaming\Anki2\addons21\323026909\insertlink.py", line 143, in insertAnchor
    self.editor.web.eval("focusField(%d);" % self.editor.currentField)
TypeError: %d format: a number is required, not NoneType
```

**Comment by firejake308** [comment]
Fixed as of today
